### ISSUE TITLE
Lost focus when edit title

### ISSUE THREAD

**Issue by lika8701** [grafviktor/goto#1]
To reproduce - create several items in the database, let all titles will be the same:

- A title 1
- A title 2
- A title 3
- A title 4
- A title 5

Rename title of item "**A** title 2" to  "**B** title 2", save the changes. You will see that a different item is now selected, not which you edited. That's very annoying when you have more than 10 records.

**Comment by grafviktor** [comment]
Thank you! Will be fixed in 1.0.1. 
The fix has been merged [PR2](https://github.com/grafviktor/goto/pull/2/files) into master.
