### ISSUE TITLE
[Feature] Add option for ssh-copy-id

### ISSUE THREAD

**Issue by lhns** [grafviktor/goto#47]
For the lazy ones ;)

**Comment by grafviktor** [comment]
Ha ha ha, brilliant idea! Thank you! Adding to my roadmap 👍

**Comment by grafviktor** [comment]
Blocked by [BUG-70](https://github.com/grafviktor/goto/issues/70) because focused host isn't correctly set in the list of hosts when exit filter mode, therefore a wrong ssh key can be copied to a remote host.

**Comment by grafviktor** [comment]
Still in progress. The complexity is that Windows OS does not have pre-installed ssh-copy-id executable. Looking for workarounds which would allow to do the same, but without installing any 3rd party software.

**Comment by lhns** [comment]
Maybe the functionality can be disabled if ssh-copy-id isn't present. Windows users could then install the binary manually or leave it be.

**Comment by grafviktor** [comment]
> Maybe the functionality can be disabled if ssh-copy-id isn't present. Windows users could then install the binary manually or leave it be.

Thank you for your suggestion, also though about that! 🙂 

I think, I found a workaround will see how it works. But I'll place a warning message for Windows users for sure.
