### ISSUE TITLE
[Feature] Collapsible Description Field

### ISSUE THREAD

**Issue by Rabenherz112** [grafviktor/goto#61]
Currently, the description field takes up space even when no description is provided.

It would be awesome if a feature could be introduced that allows the description field to collapse if there is no content. (maybe as an option toggle for those who want to have more space between the hosts). So that it would make the space between entries smaller.
![image](https://github.com/grafviktor/goto/assets/66558576/b09a6300-f9ac-404d-a2a2-a020bbc6d036)

**Comment by grafviktor** [comment]
Hi @Rabenherz112 thank you for raising this. I agree, that should be done. In terms of implementation I will think how to do that properly. As you suggest, I will probably create a keyboard shortcut which can be used to hide or display description fields. Additional option would be to hide this field automatically when visible area is too small.

I can make it conditinal for every record and display description only when the description exists, however it will complicate the rendering logic and the items in the list will look inconsistent. In my opinion, it would be better to rely on users' manual choice and let them to decide whether hide or display this field for all items at once.
