### ISSUE TITLE
[Feature] Support ProxyJump

### ISSUE THREAD

**Issue by konkere** [grafviktor/goto#72]
Support ProxyJump (ssh over Jumphost to host)

**Comment by grafviktor** [comment]
Hello, @konkere ! 

I think, we can do this already 🙂 Just type in your ssh parameters right into the `Host` field. Don't prefix your parameters with `ssh`, as it will be done automatically. The field label will also be changed from `Host` to `Command`. Something like that:

<img width="481" alt="jump_host" src="https://github.com/grafviktor/goto/assets/6890447/b25d4a9e-4025-4e01-a540-5f1a427b3f37">

**Comment by konkere** [comment]
@grafviktor it works!
Thanx!
