### ISSUE TITLE
[Feature]: Add a link to `aur` archlinux repo

### ISSUE THREAD

**Issue by windx-foobar** [grafviktor/goto#81]
Hello. Thanks for the project.  

### Description

I've added instructions for installing this software via `aur` in `archlinux`. It might be useful to provide a link in the documentation.

[link](https://aur.archlinux.org/packages/goto-ssh-bin)

**Comment by grafviktor** [comment]
Hi Artem. Thanks very much! I’m currently on vacation. Will take a look within several days.

**Comment by grafviktor** [comment]
Hi Artem, thanks again for your help! I'm not an expert in Arch. Could you please review the readme file changes. Please feel free to adjust where it is necessary.

https://github.com/grafviktor/goto/pull/82
